### ISSUE TITLE
How to compute the DENSITY?

### ISSUE THREAD

**Issue by NVIDIA-JerryChen** [wavefunction91/GauXC#100]
I have a question. In periodic systems, the dimension of the density matrix is **(nkpts, nao, nao)**, but in the example(https://github.com/wavefunction91/GauXC/blob/master/tests/standalone_driver.cxx#L212), the dimension of the density matrix is **(nao, nao**). I have a naive question, how should correctly handle the density matrix of periodic systems as input for GauXC?

**Comment by wavefunction91** [comment]
Just saw this - per #64 , GauXC does not currently support PBC, but it's something we're interested in. Closing in favor of that issue.
