### ISSUE TITLE
Catch2 Tag for Fetching Content

### ISSUE THREAD

**Issue by dmclark17** [wavefunction91/GauXC#26]
I was making a clean build and it looks like that Catch2 has recently retired their master branch and moved to devel as the default. This was causing the configuration step to fail on my machine.

Specifying the [v2.13.2](https://github.com/catchorg/Catch2/releases/tag/v2.13.2) tag in the [fetch content here](https://github.com/wavefunction91/GauXC/blob/4828dad0df9f269ed4959f9cd45dd5d2e62f5389/tests/CMakeLists.txt#L6) seems to fix the problem.

**Comment by wavefunction91** [comment]
Good catch! thanks for reporting. It seems that a lot of folks are waking up to this today....
