### ISSUE TITLE
nprim_pair_max is too small

### ISSUE THREAD

**Issue by dmejiar** [wavefunction91/GauXC#56]
The parameter `nprim_pair_max` is too small for many combinations of atoms and basis sets. For example, C/cc-pvqz, Ar/cc-pvdz, Fe/cc-pvdz will lead to the following error:

```
terminate called after throwing an instance of 'GauXC::generic_gauxc_exception'
  what():  Generic GauXC Exception (Too Many Primitive Pairs)
  File     /Users/meji656/Sources/exachem-dev/build/TAMM_External-prefix/src/TAMM_External-build/GauXC_External-prefix/src/GauXC_External/include/gauxc/shell_pair.hpp
  Function void GauXC::ShellPair<F>::generate(const_shell_ref, const_shell_ref) [with F = double; const_shell_ref = const GauXC::Shell<double>&]
  Line     70
```

**Comment by wavefunction91** [comment]
We are aware of this restriction and are working on a performant fix. Unfortunately, simply setting `nprim_pair_max` to a large value will trigger poor memory usage in the GPU kernels (as it's compile time). If you're focusing on just getting something to run on CPUs, we can provide an override in the interim.
