### ISSUE TITLE
UKS inputs require non-canonical scaling factors

### ISSUE THREAD

**Issue by wavefunction91** [wavefunction91/GauXC#76]
Currently, the UKS API has the following calling signature
```
[EXC, VXC_S, VXC_Z] = INTEGRATOR(D_S, D_Z);
```
where $D_s = \frac{1}{2}(D_\alpha + D_\beta)$ and $D_z = \frac{1}{2}(D_\alpha - D_\beta)$, etc. Although these are the formally correct factors in the Pauli expansion

$$
D^{UKS} = D_s \otimes I_2 + D_z \otimes \sigma_z
$$

it is more canonical to externally handle the additional factors of $\frac{1}{2}$ such that $D_s$ and $D_z$ carry the physical interpretations of the total- and spin-densities, respectively. We should also use this convention to avoid unnecessary confusion (HT @ajaypanyala)

**Comment by dmejiar** [comment]
@wavefunction91 You mention "it is more canonical to externally handle ...". but this is what is already needed, right? 

Do you mean "internally handle" and, at some point, we will need to remove the 1/2 factors on our side?

**Comment by wavefunction91** [comment]
Yes, the factors of a half have to live somwhere, but the point I was making is that $D_\alpha + D_\beta$, etc physically mean something, whereas  $\frac{1}{2}(D_\alpha + D_\beta)$ doesn't in any canonical sense. I prefer to write the Pauli expansion as

$$
D = \frac{1}{2}D_s\otimes I_2 + \frac{1}{2}\sum_{i\in\{x,y,z\}} D_i \otimes \sigma_i 
$$

i.e. the factors of $\frac{1}{2}$ are managed externally to $D_s$, etc.

On the `ExaChem` side, yes, this will require moving the factors of 1/2 from `D` to `VXC`, as I would have originally intended it.

**Comment by wavefunction91** [comment]
@dmejiar I went though the derivations again (after digging up some old notes... made the [public](http://wavefunction91.github.io/notes/) now), and it turns out that the current outputs are expected, i.e. no need to scale the output $\pm$ by $\frac{1}{2}$. Patching now, and will ping for you and @elambros to verify the workflow in your respective codes
